name: CI/CD Pipeline

on:
  push:
    branches:
      - 'review/**'   # Exécute le workflow sur les branches de review
      - main          # Exécute le workflow lors des push sur main
      - '*'           # Exécute le workflow sur toutes les branches
  pull_request:
    branches:
      - main          # Exécute le workflow lors des pull requests vers main

jobs:
  lint-format:
    name: Vérification PEP 8 et Formatage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Installer Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.4
